api/urls.py
from django.urls import path
from apps.flight_schedule.flight_schedule_api.views import FlightTaskList



urlpatterns = [
    path('scheduler/', FlightTaskList.as_view(), name="api_scheduler")
]

apps/flight_schedule/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import index, FlightListView, flights_listing

app_name='flight_scheduler'

urlpatterns = [
    path('', index, name='index'),
    path('flights/', flights_listing, name='flights')
]

core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from apps.aircraft import views
from rest_framework import routers
from django.views.generic import TemplateView
from drf_yasg.views import get_schema_view  # new
from drf_yasg import openapi  # new
from rest_framework import permissions
from django.conf import settings
from django.conf.urls.static import static

schema_view = get_schema_view(  # new
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    # url=f'{settings.APP_URL}/api/v3/',
    patterns=[path('api/', include('api.urls')), ],
    public=True,
    permission_classes=(permissions.AllowAny,),
)

router = routers.DefaultRouter()
router.register(r'aircrafts', views.AcViewSet())

urlpatterns = [
    path(  # new
        'swagger-ui/',
        TemplateView.as_view(
            template_name='swaggerui/swaggerui.html',
            extra_context={'schema_url': 'openapi-schema'}
        ),
        name='swagger-ui'),
    re_path(  # new
        r'^swagger(?P<format>\.json|\.yaml)$',
        schema_view.without_ui(cache_timeout=0),
        name='schema-json'),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/', include("api.urls")), 
    path('', include("apps.flight_schedule.urls", namespace='scheduler'))
] + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

templates/parts/navbar.html
    <nav class="navbar navbar-expand-lg navbar-light bg-dark navbar-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'scheduler:index'%}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'scheduler:flights' %}">Flights</a>
              </li>
          
              <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
              </li>
            </ul>
      
          </div>
        </div>
      </nav>